apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-http-api
spec:
  selector:
    matchLabels:
      app: python-http-api
  replicas: 1
  template:
    metadata:
      labels:
        app: python-http-api
    spec:
      containers:
      - name: python-http-api
        image: python_http_api:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /hello/JohnDoe
            port: 5000
          timeoutSeconds: 2