apiVersion: v1
kind: Service
metadata:
  name: python-http-api-service
spec:
  selector:
    app: python-http-api
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-http-api
spec:
  selector:
    matchLabels:
      app: python-http-api
  replicas: 1
  template:
    metadata:
      labels:
        app: python-http-api
    spec:
      containers:
      - name: python-http-api
        image: python_http_api:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000